Updated scripts
neptune-ai/examples pull request #147
Opened 2022-11-23 16:27 UTC by SiddhantSadangi

# Description

* Replaced "ANONYMOUS" with `neptune.ANONYMOUS_API_TOKEN` in scripts
* Updated Optuna examples with new API

__Related to:__ `update examples to use new API`

---

## ❔ This change

- [ ] adds a new feature
- [ ] fixes breaking code
- [X] is cosmetic (refactoring/reformatting)

---

## ✔️ Pre-merge checklist

Mark which items have been completed:

- [ ] Refactored code ([sourcery](https://sourcery.ai/))
- [ ] Tested code locally
- [ ] Added code to GitHub tests ([notebooks](workflows/test-notebooks.yml), [scripts](workflows/test-scripts.yml))
- [ ] Updated GitHub [README](../README.md)

### 🪝 Run the following to both [pre-commit](https://pre-commit.com/) hooks and JupyterLab (turn on `format on save`)

- [X] Stripped outputs from notebooks - ([nbstripout](https://pypi.org/project/nbstripout/))
- [X] Sorted imports - ([isort](https://pycqa.github.io/isort/))
- [X] Formatted code - ([back](https://github.com/psf/black))

### 📄 Update documentation

Coordinate with @normandy7

- [ ] Updated content in the [docs](https://docs.neptune.ai)
- [ ] Added to all relevant docs index pages (e.g., [Examples](https://docs.neptune.ai/getting-started/examples), [Integrations intro](https://docs.neptune.ai/integrations-and-supported-tools/intro), [Model training index](https://docs.neptune.ai/integrations-and-supported-tools/model-training))
- [ ] Added to examples [README](../README.md)

---

## 🧪 Test Configuration

- OS:
- Python version:
- Neptune version:
- Affected libraries with version:

---

## ✔️ Post-merge checklist

These tasks should be done after the code is merged to main. Create a subtask under the main ClickUp task to have these on your radar and share the subtask here.

__Post-merge subtask:__ `(ClickUp/JIRA task name)`

- [ ] Update relevant blogs with impacted code/functionality (Contact @Patrycja-J for the list of blogs)
- [ ] Add functionality under the Neptune column of the `competitor comparison sheet` (Coordinate with @SiddhantSadangi)
- [ ] Update integration README (Contact @Patrycja-J)

2022-11-24 06:32 UTC, normandy7 requested changes
Still seeing some `init()` calls instead of `init_run()`

2022-11-24 09:27 UTC, SiddhantSadangi commented
> Still seeing some `init()` calls instead of `init_run()`

`init()` has been changed to `init_run()` only for the optuna examples.
This is out of scope of the current PR everywhere else

2022-11-28 12:49 UTC, normandy7 submitted a review, later dismissed

2022-11-28 12:49 UTC, normandy7 commented on integrations-and-supported-tools/optuna/notebooks/Neptune_Optuna_integration.ipynb
> +    "    with_id=\"NEP1-513\", # You can pass the run ID for some other run\n",
```suggestion
    "    with_id=\"NEP1-513\", # You can pass the Neptune ID of some other run\n",
```

2022-11-28 13:27 UTC, normandy7 approved these changes

2022-11-28 13:33 UTC, merged