[WIP] add vanilla TF example
neptune-ai/examples pull request #156
Opened 2022-12-09 08:45 UTC by kshitij12345

# Description

Include a summary of the changes and the related issue.

__Related to:__ `(ClickUp/JIRA task name)`

---

## ❔ This change

- [ ] adds a new feature
- [ ] fixes breaking code
- [ ] is cosmetic (refactoring/reformatting)

---

## ✔️ Pre-merge checklist

Mark which items have been completed:

- [ ] Refactored code ([sourcery](https://sourcery.ai/))
- [ ] Tested code locally
- [ ] Added code to GitHub tests ([notebooks](workflows/test-notebooks.yml), [scripts](workflows/test-scripts.yml))
- [ ] Updated GitHub [README](../README.md)

### 🪝 Run the following to both [pre-commit](https://pre-commit.com/) hooks and JupyterLab (turn on `format on save`)

- [ ] Stripped outputs from notebooks - ([nbstripout](https://pypi.org/project/nbstripout/))
- [ ] Sorted imports - ([isort](https://pycqa.github.io/isort/))
- [ ] Formatted code - ([back](https://github.com/psf/black))

### 📄 Update documentation

Coordinate with @normandy7

- [ ] Update content in the [docs](https://docs.neptune.ai)
- [ ] (For new content) Add links to examples [README](../README.md)

---

## 🧪 Test Configuration

- OS:
- Python version:
- Neptune version:
- Affected libraries with version:

---

## ✔️ Post-merge checklist

These tasks should be done after the code is merged to main. Create a subtask under the main ClickUp task to have these on your radar and share the subtask here.

__Post-merge subtask:__ `(ClickUp/JIRA task name)`

- [ ] Update relevant blogs with impacted code/functionality (Contact @Patrycja-J for the list of blogs)
- [ ] Add functionality under the Neptune column of the `competitor comparison sheet` (Coordinate with @SiddhantSadangi)
- [ ] Update integration README (Contact @Patrycja-J)

2022-12-09 13:21 UTC, kshitij12345 commented
NOTE: Relevant TF version is not available on Python 3.11

2022-12-12 14:02 UTC, SiddhantSadangi requested changes
@kshitij12345 
Can you run the notebook through black? I see a few single quotes `'` in the code
Can you also enable source tracking (git, source code)?

2022-12-12 14:02 UTC, SiddhantSadangi commented on integrations-and-supported-tools/tensorflow/scripts/requirements.txt
> +numpy==1.21.6
```suggestion
numpy
```

2022-12-12 14:02 UTC, SiddhantSadangi commented on integrations-and-supported-tools/tensorflow/scripts/requirements.txt
> +requests==2.23.0
```suggestion
requests
```

2022-12-12 14:02 UTC, SiddhantSadangi commented on integrations-and-supported-tools/tensorflow/scripts/run_examples.sh
> +pip install -r requirements.txt
```suggestion
pip install -U -r requirements.txt
```

2022-12-12 15:52 UTC, SiddhantSadangi requested changes
Updated `showcase-run`

2022-12-12 15:52 UTC, SiddhantSadangi commented on integrations-and-supported-tools/tensorflow/notebooks/Neptune_Tensorflow.ipynb
> +    "[See this example in Neptune](https://app.neptune.ai/common/tensorflow-support/e/TFSUP-12)"
```suggestion
    "[See this example in Neptune](https://app.neptune.ai/common/tensorflow-support/e/TFSUP-101)"
```

2022-12-12 15:52 UTC, SiddhantSadangi commented on integrations-and-supported-tools/tensorflow/notebooks/Neptune_Tensorflow.ipynb
> +    "You can also check out an [example run](https://app.neptune.ai/common/tensorflow-support/e/TFSUP-12) and the corresponding [model version](https://app.neptune.ai/common/tensorflow-support/m/TFSU
```suggestion
    "You can also check out an [example run](https://app.neptune.ai/common/tensorflow-support/e/TFSUP-101) and the corresponding [model version](https://app.neptune.ai/common/tensorflow-support/m/TFSUP-TFMOD/v/TFSUP-TFMOD-25/metadata)"
```

2022-12-12 17:44 UTC, normandy7 requested changes

2022-12-12 17:44 UTC, normandy7 commented on integrations-and-supported-tools/tensorflow/notebooks/Neptune_Tensorflow.ipynb
> +    "# Saves model artifacts to `weights folder`\n",
```suggestion
    "# Saves model artifacts to "weights" folder\n",
```

2022-12-12 17:44 UTC, normandy7 commented on integrations-and-supported-tools/tensorflow/notebooks/Neptune_Tensorflow.ipynb
> +    "Refer the [documentation](https://neptune.ai/product/model-registry) for more information"
```suggestion
    "Refer to the [documentation](https://neptune.ai/product/model-registry) for more information."
```

2022-12-12 17:44 UTC, normandy7 commented on integrations-and-supported-tools/tensorflow/scripts/Neptune_Tensorflow.py
> +# Saves model artifacts to `weights folder`
```suggestion
# Saves model artifacts to "weights" folder
```

2022-12-12 17:44 UTC, normandy7 commented on integrations-and-supported-tools/tensorflow/scripts/Neptune_Tensorflow.py
> +# Refer the [documentation](https://neptune.ai/product/model-registry) for more information
```suggestion
# Refer to the [documentation](https://neptune.ai/product/model-registry) for more information
```

2022-12-13 07:51 UTC, kshitij12345 commented
@SiddhantSadangi I was thinking of updating the README once 

* this PR is merged so that we can test and correctly add the colab link and github link.
* the doc page is ready so that we have a link to the doc page.

Wdyt?

2022-12-13 07:54 UTC, kshitij12345 commented
@SiddhantSadangi @normandy7 have addressed the review. PTAL :)

2022-12-13 13:09 UTC, SiddhantSadangi commented
> @SiddhantSadangi I was thinking of updating the README once
> 
>     * this PR is merged so that we can test and correctly add the colab link and github link.
links follow the same format as existing scripts/notebooks. just have to ensure that the folder and file names are correct

>     * the doc page is ready so that we have a link to the doc page.
@normandy7 takes care of this once the docs are published

2022-12-13 13:11 UTC, SiddhantSadangi requested changes
LGTG once the readme has been updated.
We generally update this as a part of the changes so there's no lag.

2022-12-13 13:22 UTC, kshitij12345 commented
@SiddhantSadangi have updated the README. PTAL :)

2022-12-13 14:35 UTC, SiddhantSadangi requested changes

2022-12-13 14:35 UTC, SiddhantSadangi commented on README.md
> +| TensorFlow | [![docs]](https://docs.neptune.ai/integrations-and-supported-tools/model-training/tensorflow) | [![neptune]](https://app.neptune.ai/common/tensorflow-support/e/TFSUP-101) | [![github]]
```suggestion
| TensorFlow | [![docs]](https://docs.neptune.ai/integrations-and-supported-tools/model-training/tensorflow) | [![neptune]](https://app.neptune.ai/o/common/org/tensorflow-support/e/TFSUP-101/dashboard/Overview-97f6ac04-2c4b-4d10-97da-cd3a51bbeec8) | [![github]](https://github.com/neptune-ai/examples/blob/main/integrations-and-supported-tools/tensorflow/scripts) | [![colab]](https://colab.research.google.com/github/neptune-ai/examples/blob/master/integrations-and-supported-tools/tensorflow/notebooks/Neptune_Tensorflow.ipynb) |
```

2022-12-13 14:36 UTC, SiddhantSadangi approved these changes

2022-12-14 06:29 UTC, normandy7 commented on README.md
> +| TensorFlow | [![docs]](https://docs.neptune.ai/integrations-and-supported-tools/model-training/tensorflow) | [![neptune]](https://app.neptune.ai/o/common/org/tensorflow-support/e/TFSUP-101/dashboar
```suggestion
| TensorFlow | [![docs]](https://docs.neptune.ai/integrations/tensorflow) | [![neptune]](https://app.neptune.ai/o/common/org/tensorflow-support/e/TFSUP-101/dashboard/Overview-97f6ac04-2c4b-4d10-97da-cd3a51bbeec8) | [![github]](https://github.com/neptune-ai/examples/blob/main/integrations-and-supported-tools/tensorflow/scripts) | [![colab]](https://colab.research.google.com/github/neptune-ai/examples/blob/master/integrations-and-supported-tools/tensorflow/notebooks/Neptune_Tensorflow.ipynb) |
```

2022-12-14 06:30 UTC, normandy7 commented on integrations-and-supported-tools/tensorflow/notebooks/Neptune_Tensorflow.ipynb
> +    "The cell below lets you record data to the public project [common/quickstarts](https://app.neptune.ai/common/quickstarts) as an anonymous user."
```suggestion
    "The cell below lets you record data to the public project [common/tensorflow-support](https://app.neptune.ai/common/tensorflow-support) as an anonymous user."
```

2022-12-14 06:33 UTC, normandy7 commented on integrations-and-supported-tools/tensorflow/notebooks/Neptune_Tensorflow.ipynb
> +    "Tracking model with Neptune Model Registry\n",
```suggestion
    "Tracking model with Neptune model registry\n",
```

2022-12-14 06:35 UTC, normandy7 commented on integrations-and-supported-tools/tensorflow/scripts/Neptune_Tensorflow.py
> +# Tracking model with Neptune Model Registry
```suggestion
# Tracking model with Neptune model registry
```

2022-12-15 11:12 UTC, SiddhantSadangi approved these changes

2022-12-20 13:33 UTC, SiddhantSadangi requested changes
@kshitij12345 , @normandy7 
We should also rename the `tensorflow-keras` folder to just `keras`. Links will also need to be updated in the docs

2022-12-21 07:02 UTC, kshitij12345 commented
@SiddhantSadangi I think this should be out-of-scope for this PR and can be done in a separate PR. (I am conservative as it may break anything point to it and block this PR).

2022-12-21 11:18 UTC, SiddhantSadangi approved these changes

2022-12-21 11:18 UTC, SiddhantSadangi commented
> @SiddhantSadangi I think this should be out-of-scope for this PR and can be done in a separate PR. (I am conservative as it may break anything pointing to that code and block this PR).

sounds good.. we'll rename the project too with the PR

2022-12-21 11:38 UTC, normandy7 submitted a review, later dismissed
Looks good otherwise.

2022-12-21 11:38 UTC, normandy7 commented on README.md
> +| TensorFlow | [![docs]](https://docs.neptune.ai/integrations/tensorflow) | [![neptune]](https://app.neptune.ai/o/common/org/tensorflow-support/e/TFSUP-101/dashboard/Overview-97f6ac04-2c4b-4d10-97da-
Let's just remove the docs link for now. I won't have time to add a page until the 1st week of January.

```suggestion
| TensorFlow | | [![neptune]](https://app.neptune.ai/o/common/org/tensorflow-support/e/TFSUP-101/dashboard/Overview-97f6ac04-2c4b-4d10-97da-cd3a51bbeec8) | [![github]](https://github.com/neptune-ai/examples/blob/main/integrations-and-supported-tools/tensorflow/scripts) | [![colab]](https://colab.research.google.com/github/neptune-ai/examples/blob/master/integrations-and-supported-tools/tensorflow/notebooks/Neptune_Tensorflow.ipynb) |
```

2022-12-21 11:38 UTC, normandy7 commented on integrations-and-supported-tools/tensorflow/notebooks/Neptune_Tensorflow.ipynb
> +    "You can also check out an [example run](https://app.neptune.ai/common/tensorflow-support/e/TFSUP-101) and the corresponding [model version](https://app.neptune.ai/common/tensorflow-support/m/TFS
```suggestion
    "You can also check out an [example run](https://app.neptune.ai/common/tensorflow-support/e/TFSUP-101) and the corresponding [model version](https://app.neptune.ai/common/tensorflow-support/m/TFSUP-TFMOD/v/TFSUP-TFMOD-112/metadata)."
```

2022-12-21 11:38 UTC, normandy7 commented on integrations-and-supported-tools/tensorflow/scripts/Neptune_Tensorflow.py
> +# Refer to the [documentation](https://neptune.ai/product/model-registry) for more information
Could have been me that suggested this should be Markdown link formatted -- sorry about that. Realized now this is a script, not notebook.

```suggestion
# For more, refer to the documentation: https://neptune.ai/product/model-registry
```

2022-12-21 12:10 UTC, merged