add pickling learner object example
neptune-ai/examples pull request #185
Opened 2023-01-23 13:26 UTC by Blaizzy

# Description

Include a summary of the changes and the related issue.

__Related to:__ `(ClickUp/JIRA task name)`

__Any expected test failures?__ Fastai v2 doesn't export the learner in MacOS but it runs normally on linux.

---

Add a `[X]` to relevant checklist items

## ❔ This change

- [x] adds a new feature
- [x] fixes breaking code
- [ ] is cosmetic (refactoring/reformatting)

---

## ✔️ Pre-merge checklist

- [x] Refactored code ([sourcery](https://sourcery.ai/))
- [x] Tested code locally
- [x] Precommit installed and run before pushing changes
- [x] Added code to GitHub tests ([notebooks](workflows/test-notebooks.yml), [scripts](workflows/test-scripts.yml))
- [x] Updated GitHub [README](../README.md)
- [x] Updated the projects overview page on Notion

---

## 🧪 Test Configuration

- OS: MacOS ventura
- Python version: 3.8.13
- Neptune version: 0.16.15
- Affected libraries with version:

2023-01-23 14:15 UTC, SiddhantSadangi requested changes

2023-01-23 14:15 UTC, SiddhantSadangi commented on integrations-and-supported-tools/fastai/notebooks/Neptune_fastai.ipynb
> +    "learn.remove_cb(neptune_cbk)  # remove NeptuneCallback\n",
Lets mention why this is needed

2023-01-23 14:15 UTC, SiddhantSadangi commented on integrations-and-supported-tools/fastai/scripts/Neptune_fastai_more_options.py
> +# 1. (Neptune) Log a single training phase
Let's remove numbering

2023-01-23 14:15 UTC, SiddhantSadangi commented on integrations-and-supported-tools/fastai/scripts/Neptune_fastai_more_options.py
> +learn.remove_cb(neptune_cbk)  # remove NeptuneCallback
Lets mention why this is needed

2023-01-24 08:46 UTC, normandy7 approved these changes

2023-01-24 08:48 UTC, SiddhantSadangi approved these changes

2023-01-24 08:48 UTC, merged