Updated kedro example for kedro 0.18.4
neptune-ai/examples pull request #196
Opened 2023-02-06 19:57 UTC by SiddhantSadangi

# Description

Updated kedro example for kedro 0.18.4

__Related to:__ `fix test errors`

__Any expected test failures?__

---

Add a `[X]` to relevant checklist items

## ❔ This change

- [ ] adds a new feature
- [X] fixes breaking code
- [ ] is cosmetic (refactoring/reformatting)

---

## ✔️ Pre-merge checklist

- [X] Refactored code ([sourcery](https://sourcery.ai/))
- [X] Tested code locally
- [X] Precommit installed and run before pushing changes
- [ ] Added code to GitHub tests ([notebooks](workflows/test-notebooks.yml), [scripts](workflows/test-scripts.yml))
- [ ] Updated GitHub [README](../README.md)
- [ ] Updated the projects overview page on Notion

---

## 🧪 Test Configuration

- OS: Windows11
- Python version: 3.8.15
- Neptune version: 0.16.17
- Affected libraries with version: `kedro==0.18.4`, `kedro-neptune==0.1.4`

2023-02-08 07:15 UTC, normandy7 reviewed
Gave this a first cursory review. Seems like a lot of changes! Any idea what the ETA is for publishing this?

Let's sync on the changes needed to docs in the near future.

2023-02-09 14:05 UTC, Blaizzy requested changes

2023-02-09 14:22 UTC, SiddhantSadangi commented on integrations-and-supported-tools/kedro/scripts/kedro-neptune-advanced/conf/README.md
> +You can find out more about configuration from the [user guide documentation](https://kedro.readthedocs.io/en/stable/user_guide/configuration.html).
The readme is generated automatically by kedro

2023-02-12 21:37 UTC, Blaizzy commented on integrations-and-supported-tools/kedro/scripts/kedro-neptune-advanced/conf/README.md
> +You can find out more about configuration from the [user guide documentation](https://kedro.readthedocs.io/en/stable/user_guide/configuration.html).
Gotcha!
Since it doesn't exist, could you remove it?

2023-02-13 10:08 UTC, SiddhantSadangi commented on integrations-and-supported-tools/kedro/scripts/kedro-neptune-advanced/conf/README.md
> +You can find out more about configuration from the [user guide documentation](https://kedro.readthedocs.io/en/stable/user_guide/configuration.html).
I'ld rather not. Since this part (the readme) is not relevant to our integration, it should be in sync with Kedro's current state

2023-02-14 14:07 UTC, Blaizzy approved these changes
LGTM

2023-02-14 14:41 UTC, merged