Add changes to AzureML project
neptune-ai/examples pull request #221
Opened 2023-04-17 13:57 UTC by AurimasGr

Refactor to use Prophet instead of Xgboost

# Description

Include a summary of the changes and the related issue.

__Related to:__ `(ClickUp/JIRA task name)`

__Any expected test failures?__

---

Add a `[X]` to relevant checklist items

## ❔ This change

- [X] adds a new feature
- [ ] fixes breaking code
- [ ] is cosmetic (refactoring/reformatting)

---

## ✔️ Pre-merge checklist

- [ ] Refactored code ([sourcery](https://sourcery.ai/))
- [X] Tested code locally
- [ ] Precommit installed and run before pushing changes
- [ ] Added code to GitHub tests ([notebooks](workflows/test-notebooks.yml), [scripts](workflows/test-scripts.yml))
- [ ] Updated GitHub [README](../README.md)
- [ ] Updated the projects overview page on Notion

---

## 🧪 Test Configuration

- OS:
- Python version:
- Neptune version:
- Affected libraries with version:

2023-04-18 07:53 UTC, SiddhantSadangi commented
/quack review

2023-04-18 10:02 UTC, SiddhantSadangi requested changes
Do we have an Azure environment we can use to test this? If yes, we can try adding this to our test-suite

2023-04-18 13:20 UTC, AurimasGr commented on how-to-guides/azure-mlops/ml-pipelines/components/validate/validate.py
> +        name="Prophet",
Both Validation and Training runs are logged to the same run_id, we should probably retain tags just in the training step altogether.

2023-04-18 13:21 UTC, AurimasGr commented on how-to-guides/azure-mlops/ml-pipelines/components/train/train.py
> +        name="Prophet",
Both Validation and Training runs are logged to the same run_id, we should probably retain tags just in the training step altogether.

2023-04-19 07:32 UTC, normandy7 reviewed
Left some suggestions, looks good otherwise.

2023-04-19 07:32 UTC, normandy7 commented on how-to-guides/azure-mlops/ml-pipelines/README.md
> +For Azure DevOps Pipelines to be able to successfully create and execute AzureML Pipelines, you will need to create the following secrets as per ```./azure-ci/azure-pipelines.yaml``` in your Azure De
```suggestion
For Azure DevOps Pipelines to be able to successfully create and execute AzureML Pipelines, create the following secrets as per `./azure-ci/azure-pipelines.yaml` in your Azure DevOps Pipeline via the UI:
```

2023-04-19 07:32 UTC, normandy7 commented on how-to-guides/azure-mlops/ml-pipelines/README.md
> +![Screenshot 2023-04-17 at 16.32.20.png](..%2F..%2F..%2F..%2F..%2FScreenshot%202023-04-17%20at%2016.32.20.png)
Not properly uploaded/rendered (there's no such image file present)

2023-04-19 07:32 UTC, normandy7 commented on how-to-guides/azure-mlops/ml-pipelines/README.md
> +The example is focused around creation of Azure DevOps CI/CD pipeline that would be able to test the AzureML Pipeline and then deploy it for operational purposes. The following picture represents res
```suggestion
The example is focused around creation of an Azure DevOps CI/CD pipeline that would be able to test the AzureML Pipeline and then deploy it for operational purposes. The following picture shows the resulting AzureML pipeline:
```

2023-04-19 07:32 UTC, normandy7 commented on how-to-guides/azure-mlops/ml-pipelines/build_pipeline.py
> +NEPTUNE_PROJECT = "common/project-time-series-forecasting" #change to your own neptune project
```suggestion
NEPTUNE_PROJECT = "common/project-time-series-forecasting"  # change to your own Neptune project
```

2023-04-19 07:32 UTC, normandy7 commented on how-to-guides/azure-mlops/ml-pipelines/dependencies/build_environment.py
> +        # Fall back to InteractiveBrowserCredential in case DefaultAzureCredential not work
```suggestion
        # Fall back to InteractiveBrowserCredential in case DefaultAzureCredential does not work
```

2023-04-19 07:32 UTC, normandy7 commented on how-to-guides/azure-mlops/ml-pipelines/scripts/get_latest_model_prod.py
> +NEPTUNE_PROJECT = "common/project-time-series-forecasting" #change to your own neptune project
```suggestion
NEPTUNE_PROJECT = "common/project-time-series-forecasting"  # change to your own Neptune project
```

2023-05-04 10:26 UTC, AurimasGr commented on how-to-guides/azure-mlops/ml-pipelines/components/validate/validate.py
>      # Get train data
Let's skip the validated tag for now

2023-05-04 10:42 UTC, SiddhantSadangi commented on how-to-guides/azure-mlops/ml-pipelines/components/validate/validate.py
> +        name="Prophet",
To be able to filter runs

2023-05-04 13:37 UTC, SiddhantSadangi reviewed
@normandy7 - should these be in the `how-to-guides` folder or in the `integrations`  folder, where we have our `sagemaker` guide too

2023-05-04 14:12 UTC, normandy7 commented
> @normandy7 - should these be in the `how-to-guides` folder or in the `integrations` folder, where we have our `sagemaker` guide too

I agree with the comment you made a couple of weeks back -- that this content should be in `integrations-and-supported-tools`. We discussed this with @AurimasGr earlier today and he was in agreement.

2023-05-04 14:15 UTC, SiddhantSadangi requested changes
Move to `integrations-and-supported-tools/azureml`

2023-05-09 15:55 UTC, SiddhantSadangi requested changes

2023-05-09 15:55 UTC, SiddhantSadangi commented on README.md
> +| Using Neptune to track Azure ML jobs | [![docs]]( ) | [![neptune]](https://app.neptune.ai/o/common/org/project-time-series-forecasting/runs/details?viewId=standard-view&detailsTab=dashboard&dashboa
Lets move it to the Integrations and Supported tools table instead of a separate table

2023-05-10 10:19 UTC, merged