Added utils
neptune-ai/examples pull request #222
Opened 2023-04-21 09:45 UTC by SiddhantSadangi

# Description

Added utils scripts

__Related to:__ `(ClickUp/JIRA task name)`

__Any expected test failures?__

---

Add a `[X]` to relevant checklist items

## ❔ This change

- [X] adds a new feature
- [ ] fixes breaking code
- [ ] is cosmetic (refactoring/reformatting)

---

## ✔️ Pre-merge checklist

- [X] Refactored code ([sourcery](https://sourcery.ai/))
- [X] Tested code locally
- [X] Precommit installed and run before pushing changes
- [ ] Added code to GitHub tests ([notebooks](workflows/test-notebooks.yml), [scripts](workflows/test-scripts.yml))
- [ ] Updated GitHub [README](../README.md)
- [ ] Updated the projects overview page on Notion

---

## 🧪 Test Configuration

- OS: Windows11
- Python version: 3.8.15
- Neptune version: 1.1.1
- Affected libraries with version:

2023-04-21 09:56 UTC, SiddhantSadangi commented
@AurimasGr - can you also add the mlflow exporter?

2023-05-02 07:23 UTC, normandy7 reviewed
For context, is there some related task/discussion around this?

And should these be surfaced in the README, or what's the plan?

2023-05-12 15:04 UTC, normandy7 commented on utils/migration_tools/from_wandb/README.md
> +- Run logs will be created in the same folder as `wandb_to_neptune.py`. This can be adjusted by updating the `logging.basicConfig()`
```suggestion
- Run logs will be created in the same folder as `wandb_to_neptune.py`. You can change this in `logging.basicConfig()`
```

2023-05-12 15:04 UTC, normandy7 commented on utils/migration_tools/from_wandb/README.md
> +†These have been excluded at the code level to prevent redundancy and noise, but can be included.
```suggestion
† These have been excluded at the code level to prevent redundancy and noise, but can be included.
```

2023-05-12 15:04 UTC, normandy7 commented on utils/migration_tools/from_wandb/README.md
> +# Potential issues and workarounds
Looks like this can be removed? Also, if this were to be an actual heading, I'd go with "Troubleshooting" :)

2023-05-12 15:06 UTC, normandy7 requested changes
One stray heading and some nitpicking

2023-05-12 15:49 UTC, SiddhantSadangi commented on utils/migration_tools/from_wandb/README.md
> +# Potential issues and workarounds
```suggestion
```

2023-05-15 11:59 UTC, normandy7 approved these changes

2023-05-17 07:44 UTC, parthpankajtiwary approved these changes

2023-05-17 07:45 UTC, merged