Pytorch example
neptune-ai/examples pull request #224
Opened 2023-05-04 16:26 UTC by kshitij12345

# Description

Include a summary of the changes and the related issue.

__Related to:__ `(ClickUp/JIRA task name)`

__Any expected test failures?__

---

Add a `[X]` to relevant checklist items

## ❔ This change

- [ ] adds a new feature
- [ ] fixes breaking code
- [ ] is cosmetic (refactoring/reformatting)

---

## ✔️ Pre-merge checklist

- [ ] Refactored code ([sourcery](https://sourcery.ai/))
- [ ] Tested code locally
- [ ] Precommit installed and run before pushing changes
- [ ] Added code to GitHub tests ([notebooks](workflows/test-notebooks.yml), [scripts](workflows/test-scripts.yml))
- [ ] Updated GitHub [README](../README.md)
- [ ] Updated the projects overview page on Notion

---

## 🧪 Test Configuration

- OS:
- Python version:
- Neptune version:
- Affected libraries with version:

2023-05-09 17:06 UTC, kshitij12345 commented on integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch.ipynb
> +    "! pip install neptune neptune-pytorch torch torchvision numpy torchviz\n"
Will replace `neptune neptune-pytorch` with `neptune[pytorch]` once neptune 1.1.2 (or next version) is released.

2023-05-10 08:21 UTC, normandy7 requested changes

2023-05-10 08:21 UTC, normandy7 commented on integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch.ipynb
> +    "import neptune.new as neptune\n",
I've updated the Notebook template, sorry about that.

```suggestion
    "- In the bottom-left corner, expand your user menu and select **Get your API token**.\n",
    "- To copy the project name, in the top-right corner, open the settings menu and select **Properties**.\n",
    "\n",
    "### Haven't registered yet?\n",
    "\n",
    "To log anonymously to a public project, replace the code below with the following:\n",
    "\n",
    "```python\n",
    "import neptune\n",
```

2023-05-10 08:21 UTC, normandy7 commented on integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch.ipynb
> +    "import neptune as neptune\n",
```suggestion
    "import neptune\n",
```

2023-05-10 08:21 UTC, normandy7 commented on integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch.ipynb
> +    "# under the `base_namespace`.\n",
```suggestion
    "# (Neptune) The base_namespace attribute of the logger can be used to log metadata consistently\n",
    "# under the "base_namespace" namespace.\n",
```

2023-05-10 08:21 UTC, normandy7 commented on integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch.ipynb
> +    "# under the `base_namespace`.\n",
```suggestion
    "# (Neptune) The base_namespace attribute of the logger can be used to log metadata consistently\n",
    "# under the 'base_namespace' namespace.\n",
```

2023-05-10 08:21 UTC, normandy7 commented on integrations-and-supported-tools/pytorch/scripts/Neptune_Pytorch.py
> +import neptune as neptune
```suggestion
import neptune
```

2023-05-10 08:21 UTC, normandy7 commented on integrations-and-supported-tools/pytorch/scripts/Neptune_Pytorch.py
> +# under the `base_namespace`.
```suggestion
# NOTE: The base_namespace attribute of the logger can be used to log metadata consistently
# under the 'base_namespace' namespace.
```

2023-05-10 08:21 UTC, normandy7 commented on integrations-and-supported-tools/pytorch/scripts/requirements.txt
> +neptune-pytorch
Nitpick, but should it be:

```suggestion
neptune[pytorch]
```

2023-05-10 08:47 UTC, normandy7 commented on integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch.ipynb
>      "run = neptune.init_run(project=\"common/quickstarts\", api_token=neptune.ANONYMOUS_API_TOKEN)\n",
Sorry, noticed one more thing.

```suggestion
    "run = neptune.init_run(project=\"common/pytorch-integration\", api_token=neptune.ANONYMOUS_API_TOKEN)\n",
```

2023-05-10 10:07 UTC, normandy7 approved these changes

2023-05-10 13:00 UTC, normandy7 requested changes
Sorry, realized the initialization section needed some updating.

2023-05-10 13:00 UTC, normandy7 commented on integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch.ipynb
> +    "```"
We can leave this section out, as the code cell has the anonymous/public logging by default.

2023-05-10 15:47 UTC, SiddhantSadangi approved these changes

2023-05-10 15:54 UTC, merged