MLflow plugin example
neptune-ai/examples pull request #274
Opened 2023-09-21 12:26 UTC by SiddhantSadangi

# Description

Added mlflow plugin example + added mlflow exporter example to notebook

__Related to:__ MLflow integration example

__Any expected test failures?__

---

Add a `[X]` to relevant checklist items

## ❔ This change

- [X] adds a new feature
- [ ] fixes breaking code
- [ ] is cosmetic (refactoring/reformatting)

---

## ✔️ Pre-merge checklist

- [X] Refactored code ([sourcery](https://sourcery.ai/))
- [X] Tested code locally
- [X] Precommit installed and run before pushing changes
- [X] Added code to GitHub tests ([notebooks](workflows/test-notebooks.yml), [scripts](workflows/test-scripts.yml))
- [X] Updated GitHub [README](../README.md)
- [ ] Updated the projects overview page on Notion

---

## 🧪 Test Configuration

- OS: Windows11
- Python version: 3.10.11
- Neptune version: 1.6.3
- Affected libraries with version: neptune-mlflow 1.0.0.post1+561be44

2023-09-25 14:06 UTC, AleksanderWWW requested changes

2023-09-25 14:06 UTC, AleksanderWWW commented on integrations-and-supported-tools/mlflow/scripts/mlflow_neptune_plugin.py
> +        )
Shouldn't we stop the program here, if it fails to create the `data` object? Something like `sys.exit` or `raise`?

2023-09-26 13:45 UTC, normandy7 requested changes

2023-09-26 13:45 UTC, normandy7 commented on integrations-and-supported-tools/mlflow/notebooks/Neptune_MLflow.ipynb
> +    "MLflow will now start logging to Neptune"
```suggestion
    "MLflow will now start logging to Neptune."
```

2023-09-26 13:45 UTC, normandy7 commented on integrations-and-supported-tools/mlflow/notebooks/Neptune_MLflow.ipynb
> +    "# TODO: Update installation after neptune-mlflow release\n",
Should this be visible here?

2023-09-26 13:45 UTC, normandy7 commented on integrations-and-supported-tools/mlflow/notebooks/Neptune_MLflow.ipynb
> +    "        # Model registry does not work with Neptune URI\n",
Is there enough "explanatory power" in this comment? Just wondering if it could be clarified a bit here and in the script.

2023-09-26 13:56 UTC, SiddhantSadangi commented on integrations-and-supported-tools/mlflow/notebooks/Neptune_MLflow.ipynb
> +    "# to automatically log metrics and parameters to MLflow.\n",
```suggestion
```

2023-09-26 13:57 UTC, SiddhantSadangi commented on integrations-and-supported-tools/mlflow/notebooks/Neptune_MLflow.ipynb
> +    "        # Model registry does not work with Neptune URI\n",
```suggestion
```

2023-09-28 06:26 UTC, normandy7 reviewed
How is the Neptune run stopped in interactive kernels? Apparently it's not stopped within the MLflow logging context.

Examples look good otherwise.

2023-12-05 07:35 UTC, normandy7 approved these changes

2023-12-05 13:58 UTC, merged