Updated Optuna example
neptune-ai/examples pull request #322
Opened 2024-05-23 14:58 UTC by SiddhantSadangi

# Description

Updated Optuna example code

__Related to:__ Update Optuna example

__Any expected test failures?__

---

Add a `[X]` to relevant checklist items

## ❔ This change

- [X] adds a new feature
- [ ] fixes breaking code
- [X] is cosmetic (refactoring/reformatting)

---

## ✔️ Pre-merge checklist

- [X] Refactored code ([sourcery](https://sourcery.ai/))
- [X] Tested code locally
- [X] Precommit installed and run before pushing changes
- [ ] Added code to GitHub tests ([notebooks](workflows/test-notebooks.yml), [scripts](workflows/test-scripts.yml))
- [X] Updated GitHub [README](../README.md)
- [ ] Updated the projects overview page on Notion

---

## 🧪 Test Configuration

- OS: Windows11
- Python version: 3.10.11
- Neptune version: 1.10.4
- Affected libraries with version: neptune-optuna==1.2.0

2024-05-24 16:22 UTC, normandy7 requested changes

2024-05-24 16:22 UTC, normandy7 commented on integrations-and-supported-tools/optuna/notebooks/Neptune_Optuna_integration.ipynb
> +    "By default, the callback logs all the plots from the `optuna.visualization` module, details of all trials, and the Study object itself. For how to customize the NeptuneCallback further, see the
```suggestion
    "By default, the callback logs all the plots from the `optuna.visualization` module, details of all trials, and the Study object itself. For how to customize the NeptuneCallback further, see the [integration guide](https://docs.neptune.ai/integrations/optuna/#customizing-which-plots-to-log-and-how-often) in the Neptune docs."
```

2024-05-24 16:22 UTC, normandy7 commented on integrations-and-supported-tools/optuna/notebooks/Neptune_Optuna_integration.ipynb
> +    "This method is generally faster than using `NeptuneCallback`, as it doesn't log the data live. It logs the same metadata as the callback, and acdepts the same flags for customization."
```suggestion
    "This method is generally faster than using `NeptuneCallback`, as it doesn't log the data live. It logs the same metadata as the callback and accepts the same flags for customization."
```

2024-05-24 16:22 UTC, normandy7 commented on integrations-and-supported-tools/optuna/notebooks/Neptune_Optuna_integration.ipynb
> +    "1. Click **Show all** to see your trials in a separate Table View"
```suggestion
    "To compare trials within each study, group the runs by study name:\n",
    "1. Go to the runs table.\n",
    "1. Next to the search input box, click **Group by**.\n",
    "1. Type 'study/study_name' and select the field from the list.\n",
    "1. To see your trials in a separate table view, click **Show all**."
```

2024-05-24 16:22 UTC, normandy7 commented on integrations-and-supported-tools/optuna/notebooks/Neptune_Optuna_integration.ipynb
> +    "If you want to log study metadata after the Study is finished you can use the `.log_study_metadata()`.  \n",
```suggestion
    "To log study metadata after the Study is finished, use the `log_study_metadata()` function.\n",
```

2024-05-24 16:22 UTC, normandy7 commented on integrations-and-supported-tools/optuna/notebooks/Neptune_Optuna_integration.ipynb
> +    "* study-level run logged with `\"sys/tags\"=\"study\"`\n",
This is probably sufficient?

```suggestion
    "* all the trial-level runs tagged as `trial`\n",
    "* the study-level run tagged as `study`\n",
```

2024-05-27 07:16 UTC, szaganek commented on integrations-and-supported-tools/optuna/notebooks/Neptune_Optuna_integration.ipynb
> +    "## More Options"
```suggestion
    "## More options"
```

2024-05-29 13:26 UTC, merged