Revert fastai version change
neptune-ai/examples pull request #96
Opened 2022-06-27 07:04 UTC by twolodzko

For a reason unknown to me, the code with new version of fastai fails on Colab with the same exception the code with old version of fastai was failing when running script locally. I'm reverting the version used in Colab.

2022-06-27 23:24 UTC, kamil-kaczmarek commented
@twolodzko 

Can you fix it in a way that it will work in both script and colab?

2022-06-28 08:28 UTC, Blaizzy commented
@twolodzko you are getting an error on Colab because Colab by default installs PIL version 7.x.x while fastai v2.7.2+ requires PIL v9.1.1 as specified here:

https://github.com/fastai/fastai/releases/tag/2.7.2

I think it would be better to pin the PIL version instead of reverting fastai version.

`!pip install ... pillow==9.1.1`

2022-06-28 23:42 UTC, kamil-kaczmarek requested changes

2022-06-28 23:42 UTC, kamil-kaczmarek commented on integrations-and-supported-tools/fastai/notebooks/Neptune_fastai.ipynb
> +    "! pip install fastai==2.3.1 neptune-client[fastai]"
```suggestion
    "! pip install fastai==2.6.3 neptune-client[fastai]"
```

2022-06-29 03:36 UTC, kamil-kaczmarek commented
fastai tests passed, now problem is with LGBM tests -> to be fixed in separate PR.

2022-06-29 03:36 UTC, kamil-kaczmarek approved these changes

2022-06-29 03:39 UTC, kamil-kaczmarek approved these changes

2022-06-29 03:41 UTC, kamil-kaczmarek commented
Colab shows some error in installation cell, yet notebook was computer successfully till the end.

2022-06-29 03:44 UTC, merged