Fixing failing tests
neptune-ai/examples pull request #97
Opened 2022-06-28 14:47 UTC by Blaizzy

- PTL requirements
- Tensorflow requirements
- how-to-guides/how-it-works/scripts
- how-to-guides/monitor-ml-runs/scripts

2022-06-28 14:48 UTC, Blaizzy commented
@kamil-kaczmarek no action is needed at the moment here. This is still in progress, I'm just running the tests to analyze them and see if my tests take any effect.

2022-06-28 16:50 UTC, Blaizzy commented
@kamil-kaczmarek, all tests are passing!

You can review it.

Notes: 

I fixed all issues. Most were about downgrading the versions of the libraries because I noticed that some errors said that the specified higher version of the library doesn't exist while it exists.

Example:
`ERROR: No matching distribution found for tensorflow==2.7.2`

Proof of that exists in Pypi: https://pypi.org/project/tensorflow/2.7.2/

I did some research and saw that it could be related to the Python version of the machine. In our case, we are using v3.6, while TF 2.7.2 might require v3.7+.

https://github.com/tensorflow/tensorflow/issues/53709#issuecomment-1015816806

Finally, I also found out that the **dependabot** is the culprit of most of the issues, as it updates the dependencies from tested versions to higher ones without considering Python version support.
Example:
PR https://github.com/neptune-ai/examples/pull/91

2022-06-28 23:35 UTC, kamil-kaczmarek commented
@Blaizzy 
I dropped support for Python 3.6, trying to revert TF to 2.7.1

2022-06-28 23:36 UTC, kamil-kaczmarek requested changes

2022-06-28 23:36 UTC, kamil-kaczmarek commented on how-to-guides/how-it-works/scripts/requirements.txt
> +tensorflow==2.4.1
```suggestion
tensorflow==2.7.2
```

2022-06-28 23:36 UTC, kamil-kaczmarek commented on how-to-guides/monitor-ml-runs/scripts/requirements.txt
> +tensorflow==2.4.1
```suggestion
tensorflow==2.7.2
```

2022-06-28 23:36 UTC, kamil-kaczmarek commented on integrations-and-supported-tools/tensorflow-keras/scripts/requirements.txt
> +tensorflow==2.4.1
```suggestion
tensorflow==2.7.2
```

2022-06-29 01:02 UTC, kamil-kaczmarek approved these changes

2022-06-29 01:03 UTC, merged